import type { Metadata } from "next";
import { Major_Mono_Display } from "next/font/google";
import "./globals.css";

const inter = Major_Mono_Display({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
